### PR TITLE
Solves issue #73

### PR DESCRIPTION
**Pull request by mfolkeseth**
Pardon the naive approach to fixing previous versions. This is an attempt to get the ball rolling on https://github.com/eik-lib/core/issues/73.

### CODE REVIEW

**Comment by trygve-lie** [comment]
I think this looks good. I do would like to have a couple of more tests on this. 

It might exist already but if not, could you add a test which tests that we're not able to publish to an existing version? 

And I would like to have a test which tests that we're able to publish to an sparse version number. In other words if version `1.0.1` and 1.0.3` exist we test that we're able to publish to `1.0.2`.

**Comment by digitalsadhu** [comment]
I think this behaviour should require a "force" of some kind. That may just need to be in the client but should we consider adding something in core as well?

**Comment by mfolkeseth** [comment]
> I think this behaviour should require a "force" of some kind. That may just need to be in the client but should we consider adding something in core as well?

I have no strong feelings one way or the other regarding "force", but I do lean a bit in the direction that "force" belongs in a replace/overwrite context. That being said, from our perspective, we are good with either solution.

**Comment by trygve-lie** [comment]
> I do lean a bit in the direction that "force" belongs in a replace/overwrite context

On this I kinda lean in this direction too. This is a corner case when there is a sparse version in a series of versions one are publishing too and we're not overriding anything.

**Review by trygve-lie — COMMENTED** [review]
lgtm :)

Awesome work! Thanks for the PR!

**Review by trygve-lie — APPROVED** [review]

**Pull request merged**
